spring:
  datasource:
    url: jdbc:${DATABASE_URL}
    maximumPoolSize: 1
    hikari:
      connectionTimeout: 5000
      idleTimeout: 1000
      maxLifetime: 30000
      minimumIdle: 0
      maximumPoolSize: 1
  jpa:
    hibernate.ddl-auto: none